[package]
name = "bal-save"
version = "0.1.0"
edition = "2024"

[dependencies]
Inflector = "0.11.4"
eframe = "0.31.1"
egui = "0.31.1"
flate2 = "1.1.0"
futures = "0.3.31"
mlua = { version = "0.10", features = ["lua54", "vendored"] }
rfd = "0.15.3"
